
word_files = [
    ('Animal', './../Datenbank/Wörter/Nouns/Animal.csv'),
    ('Beverages', './../Datenbank/Wörter/Nouns/Beverages.csv'),
    ('Body', './../Datenbank/Wörter/Nouns/Body.csv'),
    ('Clothing', './../Datenbank/Wörter/Nouns/Clothing.csv'),
    ('Countries', './../Datenbank/Wörter/Nouns/Countries.csv'),
    ('DaysOfWeek', './../Datenbank/Wörter/Nouns/DaysOfWeek.csv'),
    ('Electronics', './../Datenbank/Wörter/Nouns/Electronics.csv'),
    ('Food', './../Datenbank/Wörter/Nouns/Food.csv'),
    ('Home', './../Datenbank/Wörter/Nouns/Home.csv'),
    ('Job', './../Datenbank/Wörter/Nouns/Job.csv'),
    ('Location', './../Datenbank/Wörter/Nouns/Location.csv'),
    ('Materials', './../Datenbank/Wörter/Nouns/Materials.csv'),
    ('Measurements', './../Datenbank/Wörter/Nouns/Measurements.csv'),
    ('Misc', './../Datenbank/Wörter/Nouns/Misc.csv'),
    ('Months', './../Datenbank/Wörter/Nouns/Months.csv'),
    ('Nature', './../Datenbank/Wörter/Nouns/Nature.csv'),
    ('People', './../Datenbank/Wörter/Nouns/People.csv'),
    ('Sport', './../Datenbank/Wörter/Nouns/Sport.csv'),
    ('Time', './../Datenbank/Wörter/Nouns/Time.csv'),
    ('Transportation', './../Datenbank/Wörter/Nouns/Transportation.csv'),
    ('Weather', './../Datenbank/Wörter/Nouns/Weather.csv'),
    ('Adjectives', './../Datenbank/Wörter/Other/Adjectives.csv'),
    ('Adverbs', './../Datenbank/Wörter/Other/Adverbs.csv'),
    ('Colour', './../Datenbank/Wörter/Other/Colour.csv'),
    ('CommonSayings', './../Datenbank/Wörter/Other/CommonSayings.csv'),
    ('Conjunctions', './../Datenbank/Wörter/Other/Conjunctions.csv'),
    ('Prepositions', './../Datenbank/Wörter/Other/Prepositions.csv'),
]

